version: '3.8'
services:
  $$cap_appname:
    image: mrstory/enrichstory-frontend:latest
    environment:
      - NEXT_PUBLIC_API_URL=https://enrich.mrstory.app/api
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$$cap_stripe_public_key
    depends_on:
      - $$cap_appname-backend
      - $$cap_appname-redis
    ports:
      - "80:3000"

  $$cap_appname-backend:
    image: mrstory/enrichstory-backend:latest
    environment:
      - DATABASE_URL=postgresql://$$cap_postgres_user:$$cap_postgres_password@srv-captain--mrs-enrichstory-db:5432/enrichstory
      - REDIS_URL=redis://$$cap_appname-redis:6379
      - JWT_SECRET_KEY=$$cap_jwt_secret
      - STRIPE_SECRET_KEY=$$cap_stripe_
      - BRAVE_API_KEY=$$cap_brave_token
    depends_on:
      - $$cap_appname-redis

  $$cap_appname-redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data: